# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/:categories/:year/:month/:day/:title

# Setup
title: 'Steven Lu'
tagline:	'tech blog'
description:	''
url:		http://blog.stevenlu.com

author:
  name:		'Steven Lu'
  url:		http://stevenlu.com

paginate:	10

social:
  - icon: info
    url: http://stevenlu.com
    desc: Visit my website

  - icon:	twitter
    url:	https://twitter.com/stevenlu
    desc:	Follow me on Twitter